### ISSUE TITLE
Remotehost parsing of simple hostname or ssh alias throws IndexError

### ISSUE THREAD

**Issue by tobigrimm** [sshuttle/sshuttle#417] opened 2020-04-07 14:33 UTC
When starting sshuttle with an alias defined in ~/.ssh/config, like the following: `./run -r paua 10.1.2.3/32` or a simple hostname as remotehost, it throws an IndexError while parsing the given remotehost (to find username/password, host and port):

```
[local sudo] Password:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)                                                                                                                                                                                         
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[...]/sshuttle/__main__.py", line 4, in <module>                                                                                                                    
    sys.exit(main())                                                                                                                                                                                              
  File "[...]/sshuttle/sshuttle/cmdline.py", line 102, in main
    opt.sudo_pythonpath)
  File "[...]/sshuttle/sshuttle/client.py", line 800, in main
    seed_hosts, auto_hosts, auto_nets, daemon, to_nameserver)                                                                                                                                                     
  File "[...]/sshuttle/sshuttle/client.py", line 458, in _main
    auto_nets=auto_nets))
  File "[...]/sshuttle/sshuttle/ssh.py", line 108, in connect
    username, password, port, host = parse_hostport(rhostport)                                                                                                                                                    
  File "[...]/sshuttle/sshuttle/ssh.py", line 89, in parse_hostport                                                                                                                  
    host = "{}".format(re.split(r'\s*@', rhostport)[1])                                                                                                                                                           
IndexError: list index out of range   
```

**Comment by j8r** [comment] 2020-04-14 12:33
Duplicate of https://github.com/sshuttle/sshuttle/issues/412

**Closed** 2020-04-14 21:05 UTC
