### ISSUE TITLE
unable to ssh tunnel to server while sshuttle is running

### ISSUE THREAD

**Issue by farshf** [sshuttle/sshuttle#382] opened 2019-11-25 16:10 UTC
Hi
I have serverA and serverB, I ssh tunnel to serverA and then run:
`sshuttle --dns -r root@serverB 0/0 -x serverB`
And all my traffic passes through serverB, just as I intend to.
Problem is that after running sshuttle on serverA, it refuses to accept new ssh tunnel connection on port 22, previously connected sessions work fine but I want to be able to ssh tunnel to serverA while it runs shuttle to serverB
How do I do that? please help me!
Thanks

**Comment by brianmay** [comment] 2019-12-01 07:46
This is not a bug but a support request; This project has limited resources for support, mostly on the mailing list, where this issue is being discussed also. Closing.

https://groups.google.com/forum/#!topic/sshuttle/f9-BzZR9C4k

**Closed by brianmay** 2019-12-01 07:46 UTC
