### ISSUE TITLE
Empty reply/EOF from server

### ISSUE THREAD

**Issue by anacrolix** [sshuttle/sshuttle#236] opened 2018-05-28 04:58 UTC
With both Mac and Linux clients, I'm getting EOF/empty replies for all connections I attempt. That is, I'm able to connect, and the remote appears to close the connection.

Without sshuttle running:

    curl: (7) Failed to connect to X port 8080: Connection refused

With:

    curl: (52) Empty reply from server

The client is running this:

    # sshuttle --dns -r somehost `somehost's ip`/32

I've tried 0.78.3, 0.78.4, and 0.76. The server has messages like this when I get EOF:

Linux:

```
server: warning: closed channel 5 got cmd=TCP_DATA len=89
server: warning: closed channel 5 got cmd=TCP_STOP_SENDING len=0
server: warning: closed channel 5 got cmd=TCP_EOF len=0
```

Mac:

`server: warning: closed channel 1 got cmd=TCP_DATA len=33`

**Comment by brianmay** [comment] 2018-05-29 07:36
Matt Joiner <notifications@github.com> writes:

> Without sshuttle running:
>
>     curl: (7) Failed to connect to X port 8080: Connection refused
>
> With:
>
>     curl: (52) Empty reply from server

This is completely normal and 100% expected.

As sshuttle operates at the Application layer, not the network layer, by
the time it works out the server has rejected the connection it is too
late to send a "Connection refused" type message as we have already
established a TCP connection. So we have no choice but to close the
connection without transferring any data.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by anacrolix** [comment] 2018-05-30 04:27
I follow that. Then why are my intended destination endpoints not being found with the configuration I'm using? It's not clear to me how to access a port listening only on localhost on a remote host. I would expect that `sshuttle --dns -r somehost somehost`, with `127.0.0.1 somehost` in `somehost`'s `/etc/hosts` would work. Have I missed something?

**Comment by brianmay** [comment] 2018-06-01 23:00
Matt Joiner <notifications@github.com> writes:

> I follow that. Then why are my intended destination endpoints not
> being found with the configuration I'm using? It's not clear to me how
> to access a port listening only on localhost on a remote host. I would
> expect that `sshuttle --dns -r somehost somehost`, with `127.0.0.1
> somehost` in `somehost`'s `/etc/hosts` would work. Have I missed
> something?

I would try:

```bash
sshuttle --dns -r somehost 127.0.0.1
```
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by anacrolix** [comment] 2018-06-04 09:10
It's definitely not forwarding over to the remote host. I ran `nc -l 6379`, and `sshuttle --dns -r somehost 127.0.0.1`, then `redis-cli`. `redis-cli` connects to the `nc` command instead of to the `redis-server` running on `somehost`. Is there any information I can provide to help solve this?

**Comment by brianmay** [comment] 2018-06-04 22:51
Matt Joiner <notifications@github.com> writes:

> It's definitely not forwarding over to the remote host. I ran `nc -l
> 6379`, and `sshuttle --dns -r somehost 127.0.0.1`, then
> `redis-cli`. `redis-cli` connects to the `nc` command instead of to
> the `redis-server` running on `somehost`. Is there any information I
> can provide to help solve this?

Sorry, I am unable to help. There coud be a number of reasons.

It did work on my computer when I tested it, but there could be
something different in your network configuration.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by ColeRominger** [comment] 2018-08-25 00:11
I am seeing this too. I am using sshuttle and making hundreds of connections an hour over sshuttle.
As these connections close they are also leaving the socket in a FIN_WAIT2 state and eating up all the file descriptors until python crashes when it reaches the process ulimit I have set in the service definition. This has been raised to 4096 to see just how many FIN_WAIT2 will accumulate. Currently the limit is 1024 and then sshuttle crashes.

**Comment by ColeRominger** [comment] 2018-08-25 00:16
I am seeing this too. I am making hundreds of connections an hour over sshuttle.
As these connections close they are also leaving the socket in a FIN_WAIT2 state and eating up all the file descriptors until python crashes when it reaches the nofile limit. I have since set LimitNOFILE=4096 to see in service definition see if any FIN_WAIT2 timeout will be reached and if sockets get pruned by the OS. Last crash was the same as the others and when the default nofile ulimit of 1024 was reached.

**Comment by ColeRominger** [comment] 2018-08-25 00:16
I am seeing this too. I am making hundreds of connections an hour over sshuttle.
As these connections close they are also leaving the socket in a FIN_WAIT2 state and eating up all the file descriptors until python crashes when it reaches the nofile limit. I have since set LimitNOFILE=4096 in service definition see if any FIN_WAIT2 timeout will be reached and if sockets get pruned by the OS. Last crash was the same as the others and when the default nofile ulimit of 1024 was reached.

**Comment by ColeRominger** [comment] 2018-08-25 00:17
I am seeing this too. I am making hundreds of connections an hour over sshuttle.
As these connections close they are also leaving the socket in a FIN_WAIT2 state and eating up all the file descriptors until python crashes when it reaches the nofile limit. I have since set LimitNOFILE=4096 in service definition see if any FIN_WAIT2 timeout will be reached and if sockets get pruned by the OS. Last crash was the same as the others when the default nofile ulimit of 1024 was reached.

**Comment by brianmay** [comment] 2018-09-23 22:29
Moving this to #264.

**Closed by brianmay** 2018-09-23 22:29 UTC

**Comment by anacrolix** [comment] 2018-09-24 00:28
I think https://github.com/sshuttle/sshuttle/issues/236#issuecomment-415913357 could be a different issue, I don't think #264 covers the original problem here.

**Comment by brianmay** [comment] 2018-09-24 00:43
You are probably right. That comment looks unrelated to this bug report, and is confusing. Will see if I can hide it. In any case, I don't think I can help with this issue, as I was not able to reproduce it myself, sorry.
