### ISSUE TITLE
using socks connection from another machine

### ISSUE THREAD

**Issue by nisuhw** [sshuttle/sshuttle#167] opened 2017-09-03 13:02 UTC
Let say that I have computer A and running `ssh -D 0.0.0.0:1080 user@server_with_internet_access` and I have computer B with chisel installed but It cannot ssh to computer A due to a very strict authentication. So the following command from computer B will fail: `ssh user_computerA@ip_computerA`
Is it possible for chisel to use socks connection from computer A directly?

something like this maybe? :
`sshuttle --dns -l 0.0.0.0 -r user_computerA@ip_computerA:1080 0/0`

**Comment by brianmay** [comment] 2017-11-07 22:14
We just use ssh to make the connections. So if ssh supports connecting via a socks proxy, then it will work. Unfortunately, I don't think ssh has this support... Although it has been a while since I last used socks.

Will close this as I don't think it is a sshuttle issue, however, will be happy to reopen if required.

**Closed by brianmay** 2017-11-07 22:14 UTC

**Comment by brianmay** [comment] 2017-11-07 22:15
I suspect this was a duplicate of #166.
