### ISSUE TITLE
Is it possible to reverse forward traffic? 

### ISSUE THREAD

**Issue by dclong** [sshuttle/sshuttle#564] opened 2020-12-04 07:50 UTC
I understand that `sshuttle` can be use to forward all traffic from a client machine C to a remote server S (via SSH tunnels). However, it is possible to use `sshuttle` to reverse forward all traffic from the remote server S to the local client C? Notice that the restriction here is that the client C can ssh to the remote server S but the remote server S cannot ssh into the client C.

**Comment by skuhl** [comment] 2021-01-03 14:44
Is this is a duplicate of #421?

**Closed** 2021-01-03 18:08 UTC
