### ISSUE TITLE
-N, --auto-nets generates c : fatal: server died with error code 255

### ISSUE THREAD

**Issue by noraj** [sshuttle/sshuttle#351] opened 2019-08-29 15:27 UTC
For example `sshuttle -vr noraj@192.168.1.80 10.42.42.0/24` is working but when I remove the subet and add `-N, --auto-nets` it keeps crashing.

```
$ sshuttle -vNr noraj@192.168.1.80             
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.7.4
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.7.4
c : connecting to server...
Password: 
Starting server with Python version 3.6.5
 s: latency control setting = True
c : Connected.
 s: auto-nets:True
 s: available routes:
 s:   2/10.42.42.0/24
 s:   2/192.168.1.0/24
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.42.42.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.1.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
client_loop: send disconnect: Broken pipe
firewall manager: undoing changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
c : fatal: server died with error code 255
```

PS : as other issues adding `-x 192.168.1.0/24` avoids fail.

## (Potential) related issues

- #191
- #257
- #193

## Versions

- sshuttle : 0.78.5
- client : 
  + python 3.7.4
  + kernel 4.19.68-1-lts (archlinux x86_64)
- server : 
  + python 3.6.5
  + kernel 4.12.14-lp151.28.13-default (openSUSE Leap 15.1 x86_64)

**Comment by brianmay** [comment] 2019-09-22 00:21
Yes, this is probably a duplicate of #191. It doesn't make sense having duplicate bug reports open, so closing this one.

**Closed by brianmay** 2019-09-22 00:21 UTC

**Comment by noraj** [comment] 2019-09-22 16:46
I was not sure it was linked
