### ISSUE TITLE
Error while connecting to higher port need fast response plz!!!EXAM Ahead

### ISSUE THREAD

**Issue by amvinayak** [sshuttle/sshuttle#526] opened 2020-09-21 15:07 UTC
when i try with higher port i face this issue my friend is using 0.78.5 he is not having issues if possible plz give me a link to download that
root@kali:/opt# sshuttle -r j0hn@10.11.1.252:22000 10.2.2.0/24 -v
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.5
firewall manager: ready method name nat.
IPv6 enabled: None
UDP enabled: False
DNS enabled: False
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.8.5
c : connecting to server...
j0hn@10.11.1.252's password: 
Traceback (most recent call last):
  File "<string>", line 1, in ?
  File "assembler.py", line 18, in ?
TypeError: module.__init__() argument 1 must be string, not unicode
c : fatal: server died with error code 1
root@kali:/opt#

**Comment by AdibHurtadoOlson** [comment] 2020-09-21 15:19
I haven't had time to look through all of the code, however, it seems like you are decoding "ASCII" (on line 14 of assembler.py); is there any possibility it is using some other encoding format?

**Comment by brianmay** [comment] 2020-09-21 21:45
When sshuttle connects to the remote server, it sends a copy of itself to the server that is then run, and the communication protocol is ASCII only. If you are getting non-ASCII characters that would suggest something is going wrong, and it isn't going to work anyway.

Does ssh by itself to the server work fine?

**Comment by mkesper** [comment] 2020-12-11 09:02
I can reproduce this when using Python3.8+

**Comment by mkesper** [comment] 2021-02-05 07:34
Seems to be fixed with version 1.0.5.

**Closed** 2021-02-05 09:56 UTC
