### ISSUE TITLE
Fails to connect to endpoints with Python 3.8

### ISSUE THREAD

**Issue by fredronnv** [sshuttle/sshuttle#381] opened 2019-11-22 05:50 UTC
Endpoints that have been updated with python 3.8 seem to cause issues with sshuttle.

```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.0
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.8.0
c : connecting to server...
assembler.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Starting server with Python version 3.8.0
 s: latency control setting = True
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 38, in <module>
  File "sshuttle.server", line 298, in main
  File "/usr/lib/python3.8/socket.py", line 544, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket
c : Connected.
c : fatal: server died with error code 1
```

Older python endpoinds are fine:
```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.0
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.8.0
c : connecting to server...
Starting server with Python version 2.6.6
 s: latency control setting = True
c : Connected.
 s: auto-nets:False
firewall manager: setting up.
[...]
```

**Comment by brianmay** [comment] 2019-11-22 06:46
Looks like `socket.fromfd()` may have been changed to only work on sockets. stdin/stdout is not a socket. Which possible is a regression in Python 3.7. Alternatively it also begs the question: why are we doing this? It probably doesn't make sense to try to pretend stdin/stdout is a socket- which is exactly what we appear to be doing.

**Comment by dvs999** [comment] 2019-12-11 13:11
Has anyone a proper solution for this? 

For anyone looking at a temporary workaround, I've used pyenv on the destination to install Python 3.7.5 and passed in the location of the server python binary on the client command line --python /home/rob.hall/.pyenv/versions/3.7.5/bin/python Not ideal but it works until a patch can be produced.

**Comment by brianmay** [comment] 2019-12-11 20:47
I suspect that fixing properly this might require changing the classes in ``ssnet.py`` to use filehandles (or something else) instead of sockets (because stdin/stdout isn't actually socket). Which may or may not be as easy as it sounds.

Unfortunately I don't have time to look at this right now.

**Comment by brianmay** [comment] 2019-12-11 21:01
I believe this is the [line](https://github.com/sshuttle/sshuttle/blob/6ad4473c87511bcafaec3d8d0c69dfcb166b48ed/sshuttle/server.py#L297) where it is failing.

**Comment by jwilk** [comment] 2019-12-19 17:10
https://bugs.python.org/issue35415

**Comment by ryanmjacobs** [comment] 2019-12-21 18:15
@dvs999 Your solution worked for me :+1:

It's kinda kludgey but it's letting me get some work done finally. I'm visiting relatives and their Comcast network has some stupid firewalls that block certain ports unless I'm on a VPN.

For future reference, I'm on Arch Linux. I installed `pyenv` via Pacman.
```sh
# server-side
$ sudo pacman -S pyenv
$ pyenv install 3.7.5
```
```sh
# client-side
$ sshuttle --python=/home/ryan/.pyenv/versions/3.7.5/bin/python --dns -r server.com 0/0
```

**Comment by myself379** [comment] 2020-01-09 15:48
Hi guys, @ryanmjacobs how do you get install 3.7.5? I'm keep having errors on C compiler cannot create executables, even though I did `pkg install build-essentials`

**Comment by ryanmjacobs** [comment] 2020-01-09 19:32
@myself379 What OS are you using?

**Comment by myself379** [comment] 2020-01-11 00:57
Hi everyone,

I solved my but I just wanna share it out here so that others might be closer to the solutions.

My setup/requirements:

- Xiaomi A1 Android Pie (API=28), stocked rooted. Termux installed (just apt apt-get, not Arch Linux pacman)
- goal: use sshuttle as SSH Tunnel/VPN connected via Hotspot shared by Phone (I tried on 5 Ghz and it worked)
- Python must be installed and enabled in Server side; in this case its Phone Termux
- Client must using sshuttle (just git clone is fine, or use pacman -Sy sshuttle)
- Termux is using pyenv to get different version of Python

Problem: Python 3.8 is not working for sshuttle and it crashes. Need to revert to older Python version. Unfortunately, you need to recompile the Python source code of your choice of versions. Which complicates because you need build-tools. For my case, not all version work, for me Python 3.7.5 couldn't compile due to getrandom() error, Python 2.x give me weird problems and failed in compilation. Only version Python 3.6.9 get me the closes to successful compilation.

# Installing pyenv on Termux Android
```bash
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
```

I just follow instruction here [gwangyi.github.io](https://gwangyi.github.io/posts/pyenv-in-termux/)

# Problem faced and solutions

```bash
# Install Python by downloading and compiling
pyenv install 3.6.9 -k -vvv

# Make sure you have build-essential tools
pkg install build-essential
```
Define 
```bash
export __ANDROID_API__=28
export LDFLAGS='-L/system/lib/'
export CFLAGS='-I/data/data/com.termux/files/usr/include/'
```

`LDFLAGS` and `CFLAGS` tells your gcc compiler where to look for lib during compilation. I have no elegant solution for `__ANDROID_API__`, in the end I just edit the ./configure file in in the `Python-3.6.9` source file.

`zlib.h` is located in `/data/data/com.termux/files/usr/include/`
`libz.so` is located in `/system/lib/` or you can specify in `/data/data/com.termux/files/usr/lib/`

just make sure both is the same version, my case is 1.2.11 

For my case, `pyenv install 3.6.9 -k -vvv` fails due to zlib library was not found and unable to decompress. This is the final piece of the puzzle. You need to enabled it in your `.pyenv/sources/3.6.9/Python-3.6.9/Modules/Setup` and uncomment the `zlib` line.

now your `make && make install` should be working.

# Useful steps to know
```bash
`pyenv install` is actually multiple steps

# It starts at 
./configure --prefix='$PREFIX'
# $PREFIX should be pointed to $FULLPATH/.pyenv/versions/3.6.9
# Then
make
# Finally. Termux only have tsudo instead of sudo
tsudo make install
```

**Comment by brianmay** [comment] 2020-02-19 06:09
I filled a Python bug report on this. https://bugs.python.org/issue39685

I am uncertain where this needs to be fixed, hopefully the above can provide some clarity.

**Comment by nepella** [comment] 2020-05-05 21:43
I encountered this after updating a target host to Ubuntu 20.04; Python 2 was still installed, and adding `--python /usr/bin/python2` to the `sshuttle` invocation solved the problem.

**Comment by PresGas** [comment] 2020-05-06 12:00
I can confirm @nepella 's workaround. I am pasting the args and output if that will help. Client is Ubuntu 20.04, target is Ubuntu 20.04:

```
sudo sshuttle @/home/user/.config/sshuttle.conf --python /usr/bin/python -v
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.2
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 3.8.2
c : connecting to server...
user@ubuntu.fq.dn's password: 
Starting server with Python version 2.7.18rc1
 s: latency control setting = True
 s: auto-nets:False
c : Connected.
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
...etc...
```

I did not have to put in the `--python` option when I used as the target a RHEL 7.7 machine while the client was still Ubuntu 20.04:

```
sudo sshuttle @/home/user/.config/sshuttle-research.conf -v
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.2
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 3.8.2
c : connecting to server...
Password: 
Starting server with Python version 2.7.16
 s: latency control setting = True
 s: auto-nets:False
c : Connected.
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
...etc...
```

This is the output for 20.04 and 20.04 without the `--python` arg:

```
sudo sshuttle @/home/user/.config/sshuttle.conf -v
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.2
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 3.8.2
c : connecting to server...
user@ubuntu.fq.dn's password: 
assembler.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Starting server with Python version 3.8.2
 s: latency control setting = True
c : Connected.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 38, in <module>
  File "sshuttle.server", line 298, in main
  File "/usr/lib/python3.8/socket.py", line 544, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket
c : fatal: server died with error code 1
```

**Comment by normanr** [comment] 2020-05-10 19:59
Is the wrapping required? Could you just pass stdin & stdout to Mux as-is?

**Comment by brianmay** [comment] 2020-05-10 22:05
Good question. I imagine Mux may require a bit of changing, because it assumes it has a socket, not a file. Plus the values are stored in the object using "rsock" and "wsock" which strongly implies that they are sockets. Plus these names imply public access is possible (this may not happen however).

I suspect this might be the correct way to fix this however.

**Comment by normanr** [comment] 2020-05-10 22:31
It looks like stdin/stdout might already support most of the methods that are used (from the python bug report: setblocking, select, read, write, shutdown). setblocking can be replaced with os.set_blocking (Py3.5+), select should work as-is, as so should read & write. I don't know if shutdown ever worked (it's in a try/except block already).

You could make the code use sockets <3.8 and os.set_blocking >=3.8.

**Comment by brianmay** [comment] 2020-05-14 22:01
I had an attempt to fix this in #431, although I think I broke Python <= 3.5 due to the set_blocking call.

**Comment by brianmay** [comment] 2020-05-28 21:48
I merged #431, so I think I can close this now.

**Closed by brianmay** 2020-05-28 21:48 UTC

**Comment by pmorch** [comment] 2020-07-14 07:39
FYI: I've filed this bug report against the Ubuntu sshuttle package: https://bugs.launchpad.net/ubuntu/+source/sshuttle/+bug/1887489

**Comment by honarkhah** [comment] 2020-09-02 04:51
> FYI: I've filed this bug report against the Ubuntu sshuttle package: https://bugs.launchpad.net/ubuntu/+source/sshuttle/+bug/1887489

https://bugs.launchpad.net/ubuntu/+source/sshuttle/+bug/1873368
