### ISSUE TITLE
Fatal: server died with error code 255

### ISSUE THREAD

**Issue by xarkes** [sshuttle/sshuttle#193] opened 2017-12-18 13:42 UTC
Hi, I am getting this error when trying to connect to myssh server.
```
$ sshuttle -r myremoteserver 0/0 -v
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.6.3
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.6.3
c : connecting to server...
Starting server with Python version 3.4.2
 s: latency control setting = True
 s: available routes:
c : Connected.
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 42
packet_write_wait: Connection to xxx.xxx.xxx.xxx port 22: Broken pipe
firewall manager: undoing changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
c : fatal: server died with error code 255
```
I am currently using
```
$ sshuttle -V
0.78.4.dev31+g512396e
```

I tried with various versions of sshuttle. I don't know how I am supposed to debug it.
Thanks in advance.

**Comment by nstetter** [comment] 2017-12-21 06:13
Same for me.
It works very inconsistently though without changing any parameters. Just by retrying it did't crash in ~5% of the cases.
Let me know if I can do anything to help debug the issue.

**Comment by brianmay** [comment] 2017-12-23 07:57
xarkes <notifications@github.com> writes:

> c : fatal: server died with error code 255

This basically means that the ssh process died.

Sorry, I have no idea why. Possibly making it more verbose mode (-vvv)
might help?

(It is also possible that the ssh process is dieing because its packets
are being being redirected through sshuttle - I don't think that should
be happening here however)
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by zainryan** [comment] 2017-12-27 03:49
I can confirm. Originally, sshuttle works fine for me. However, after updating my kernel version from 4.12.12 to 4.14.8, sshuttle will crash with error code 255 in high probability. I think the latest kernel has some modification in network stack which is related to this error.

**Comment by zainryan** [comment] 2017-12-27 04:50
I have done a simple trace and finally found that the server side process is dead at the line 588 of ssnet.py.
`    (r, w, x) = select.select(r, w, x)`

**Comment by brianmay** [comment] 2017-12-27 22:48
I am going to assume this is the same as #191 unless I find out otherwise. Please see #191.

I am going to close this bug report for now, unless there is some indication it is a different problem.

**Closed by brianmay** 2017-12-27 22:48 UTC

**Comment by ariananggada** [comment] 2018-01-07 11:55
i am using kernel version:
4.14.12-1-ARCH

and got a same problem. after several tries i ended up using param --exclude(your server ip you want to remote).works well

sshuttle --dns --exclude xxx.xxx.xxx.xxx -vr xxx.xxx.xxx.xxx 0/0
