### ISSUE TITLE
`TypeError: module.__init__() argument 1 must be string, not unicode` in assembler.py

### ISSUE THREAD

**Issue by LeifW** [sshuttle/sshuttle#484] opened 2020-07-06 22:21 UTC
In version 1.0.2,
invoking:
```
sshuttle -vv --ssh-cmd "$SSH_CMD" --dns -r myuser@myhostname.com:2222 172.42.0.0.0/16
```
gives:
```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.3
firewall manager: ready method name nat.
IPv6 enabled: None
UDP enabled: False
DNS enabled: True
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Binding DNS: 12300 12299
DNS listening on ('127.0.0.1', 12299).
DNS listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12299)>.
Starting client with Python version 3.8.3
c : connecting to server...
c : executing: ['ssh', '-o', 'IdentitiesOnly=yes', '-i', './foo.pem', '-p', '2222', 'myuser@myhostname.com', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1279), "assembler.py", "exec"))\'"\'"\'\'']
c : > channel=0 cmd=PING len=7 (fullness=0)
load pubkey "./foo.pem": invalid format
server: assembling u'sshuttle' (88 bytes)
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "assembler.py", line 18, in <module>
TypeError: module.__init__() argument 1 must be string, not unicode
c : fatal: server died with error code 1
```

**Comment by brianmay** [comment] 2020-07-06 22:49
I think this is a duplicate of #481

**Comment by codethought** [comment] 2020-07-07 18:25
This pretty much killed my development..

**Comment by brianmay** [comment] 2020-07-07 21:03
I will close this in favor of #481. Having multiple bug reports open for the same bug only causes confusion. Please subscribe to that bug report.

In addition you are welcome to trouble shoot why this is happening and submit a pull request...

**Closed by brianmay** 2020-07-07 21:03 UTC
