### ISSUE TITLE
Sshuttle not working over OpenVPN Tunnel

### ISSUE THREAD

**Issue by craigwatson** [sshuttle/sshuttle#102] opened 2016-06-23 09:41 UTC
My scenario: I'm running OSX El Capitan, and sometimes work remotely and need to connect to my company's OpenVPN server in order to hook into ACLs and firewalls set up by our customers - this connection is set up to route all traffic over the VPN. I also need to use sshuttle to connect to remote networks behind bastion hosts in our customers' infrastructure.

When using sshuttle and OpenVPN individually, everything works as intended, however when using sshuttle after connecting to an OpenVPN tunnel, the firewall proxy rules don't take effect.

I'm aware that this could be due to OpenVPN _or_ sshuttle, however colleagues running Linux can connect with no problem, so I suspect this is due to sshuttle using pf rather than iptables on Mac.

Can anyone help resolve this? Happy to provide more detail if necessary.

**Comment by vieira** [comment] 2016-06-23 14:56
Hello @craigwatson,

I have an idea about what might be causing this issue, but I don't have OpenVPN to test right now on OSX. When you say that the rules don't take effect are you referring to the rules installed by OpenVPN or by sshuttle? Does the VPN connection still work after running sshuttle, i.e., are you able to reach, e.g, the bastion hosts?

**Comment by craigwatson** [comment] 2016-06-23 15:03
Hi @vieira,

The VPN connection works, and I can SSH into the bastion hosts manually, and sshuttle also reports connected, but traffic that should be forwarded via sshuttle isn't.

When I disconnect from the OpenVPN and run sshuttle to a network directly, traffic is routed correctly via the remote SSH host.

Hope that's clear enough :)

**Comment by vieira** [comment] 2016-06-23 18:38
Ah I see, thanks. That was not what I was expecting. I will take a look.

**Comment by vieira** [comment] 2016-06-23 20:29
Hi again @craigwatson,

Could you please post the output  of (translation rules and filter rules is enough, I think) `sudo pfctl -sa` with only OpenVPN running and then with both OpenVPN and sshuttle running?

Thanks in advance.

**Comment by craigwatson** [comment] 2016-06-23 20:33
No problem.

Only OpenVPN:
```
craig@zeus:~$ sudo pfctl -sa
Password:
No ALTQ support in kernel
ALTQ related functions disabled
TRANSLATION RULES:
rdr-anchor "sshuttle" all

FILTER RULES:
pass on lo all flags S/SA keep state
anchor "sshuttle" all

INFO:
Status: Disabled for 0 days 01:32:48          Debug: Urgent

State Table                          Total             Rate
  current entries                        0
  searches                         1462101          262.6/s
  inserts                             1333            0.2/s
  removals                            1333            0.2/s
Counters
  match                            1062202          190.8/s
  bad-offset                             0            0.0/s
  fragment                               0            0.0/s
  short                                  0            0.0/s
  normalize                              0            0.0/s
  memory                                 0            0.0/s
  bad-timestamp                          0            0.0/s
  congestion                             0            0.0/s
  ip-option                            111            0.0/s
  proto-cksum                            0            0.0/s
  state-mismatch                      1331            0.2/s
  state-insert                          34            0.0/s
  state-limit                            0            0.0/s
  src-limit                              0            0.0/s
  synproxy                               0            0.0/s
  dummynet                               0            0.0/s

TIMEOUTS:
tcp.first                   120s
tcp.opening                  30s
tcp.established           86400s
tcp.closing                 900s
tcp.finwait                  45s
tcp.closed                   90s
tcp.tsdiff                   30s
udp.first                    60s
udp.single                   30s
udp.multiple                 60s
icmp.first                   20s
icmp.error                   10s
grev1.first                 120s
grev1.initiating             30s
grev1.estblished           1800s
esp.first                   120s
esp.estblished              900s
other.first                  60s
other.single                 30s
other.multiple               60s
frag                         30s
interval                     10s
adaptive.start             6000 states
adaptive.end              12000 states
src.track                     0s

LIMITS:
states        hard limit    10000
app-states    hard limit    10000
src-nodes     hard limit    10000
frags         hard limit     5000
tables        hard limit     1000
table-entries hard limit   200000

OS FINGERPRINTS:
696 fingerprints loaded
```

With OpenVPN and sshuttle:

```
craig@zeus:~$ sudo pfctl -sa
No ALTQ support in kernel
ALTQ related functions disabled
TRANSLATION RULES:
rdr-anchor "sshuttle" all

FILTER RULES:
pass on lo all flags S/SA keep state
anchor "sshuttle" all

INFO:
Status: Enabled for 0 days 00:00:03           Debug: Urgent

State Table                          Total             Rate
  current entries                        0
  searches                         1462539       487513.0/s
  inserts                             1333          444.3/s
  removals                            1333          444.3/s
Counters
  match                            1062402       354134.0/s
  bad-offset                             0            0.0/s
  fragment                               0            0.0/s
  short                                  0            0.0/s
  normalize                              0            0.0/s
  memory                                 0            0.0/s
  bad-timestamp                          0            0.0/s
  congestion                             0            0.0/s
  ip-option                            111           37.0/s
  proto-cksum                            0            0.0/s
  state-mismatch                      1331          443.7/s
  state-insert                          34           11.3/s
  state-limit                            0            0.0/s
  src-limit                              0            0.0/s
  synproxy                               0            0.0/s
  dummynet                               0            0.0/s

TIMEOUTS:
tcp.first                   120s
tcp.opening                  30s
tcp.established           86400s
tcp.closing                 900s
tcp.finwait                  45s
tcp.closed                   90s
tcp.tsdiff                   30s
udp.first                    60s
udp.single                   30s
udp.multiple                 60s
icmp.first                   20s
icmp.error                   10s
grev1.first                 120s
grev1.initiating             30s
grev1.estblished           1800s
esp.first                   120s
esp.estblished              900s
other.first                  60s
other.single                 30s
other.multiple               60s
frag                         30s
interval                     10s
adaptive.start             6000 states
adaptive.end              12000 states
src.track                     0s

LIMITS:
states        hard limit    10000
app-states    hard limit    10000
src-nodes     hard limit    10000
frags         hard limit     5000
tables        hard limit     1000
table-entries hard limit   200000

TABLES:

OS FINGERPRINTS:
696 fingerprints loaded
```

**Comment by vieira** [comment] 2016-06-23 22:05
@craigwatson Thanks a lot. I thought some skip lo might have ended up on the chain, but that doesn't seem to be the case. 😞
With OpenVPN running, could you please run sshuttle with `-vvv` and then execute `pfctl -a sshuttle -sr` and share both outputs, just to be sure our rules are there?

**Comment by vieira** [comment] 2016-06-23 22:39
Another thing I would like to check is if the range that is going through OpenVPN contains the subnets that you are trying to rdr with sshuttle. If that's the case it might explain the problem. `netstat -nr` (with the VPN running) should show your routing tables, including the ranges that are being routed through OpenVPN's tun.

**Comment by craigwatson** [comment] 2016-06-24 09:09
Hi @vieira,

Here we go (IP addresses redacted):

```
craig@zeus:~$ sshuttle -vvv -r craig@x.x.x.x 10.10.216.0/22
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.10
firewall manager: ready method name pf.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x1083a0130>.
Starting client with Python version 2.7.10
c : connecting to server...
c : executing: ['ssh', 'craig@x.x.x.x', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(958), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (8 bytes)
server: assembling u'sshuttle.cmdline_options' (27 bytes)
server: assembling u'sshuttle.helpers' (950 bytes)
server: assembling u'sshuttle.ssnet' (5540 bytes)
server: assembling u'sshuttle.hostwatch' (2364 bytes)
server: assembling u'sshuttle.server' (3091 bytes)
Starting server with Python version 2.6.6
 s: latency control setting = True
 s: available routes:
 s:   2/10.10.217.160/28
 s:   2/10.10.217.160/28
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=38 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=45/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=45/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 46/46
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=45/0)
c : Connected.
c : Waiting: 2 r=[4, 8] w=[8] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[8] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=38
firewall manager: Got subnets: [(2, 22, False, '10.10.216.0'), (2, 8, True, '127.0.0.1')]
firewall manager: Got nslist: []
firewall manager: Got ports: 0,12300,0,0
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv4.
>> pfctl -f /dev/stdin
>> pfctl -s all
rules:
---> table <forward_subnets> {10.10.216.0/22,!127.0.0.1/8}
---> rdr pass on lo0 proto tcp to <forward_subnets> -> 127.0.0.1 port 12300
---> pass out route-to lo0 inet proto tcp to <forward_subnets> keep state
>> pfctl -a sshuttle -f /dev/stdin
>> pfctl -E
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[4, 8] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=45)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
c :   Ready: 2 r=[8] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c : Waiting: 2 r=[4, 8] w=[] x=[] (fullness=0/0)
```

```
craig@zeus:~$ sudo pfctl -a sshuttle -sr
No ALTQ support in kernel
ALTQ related functions disabled
pass out route-to lo0 inet proto tcp from any to <forward_subnets> flags S/SA keep state
```

```
craig@zeus:~$ sudo netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
0/1                10.200.200.93      UGSc           15        0   utun3
default            192.168.1.254      UGSc           16        0     en0
10.200.200.1/32    10.200.200.93      UGSc            2        0   utun3
10.200.200.93      10.200.200.94      UHr            34       18   utun3
54.76.122.23/32    192.168.1.254      UGSc            3        0     en0
127                127.0.0.1          UCS             2        0     lo0
127.0.0.1          127.0.0.1          UH             15    88359     lo0
127.94.0.1         127.94.0.1         UH              2        0     lo0
127.94.0.2         127.94.0.2         UH              2        0     lo0
128.0/1            10.200.200.93      UGSc           16        0   utun3
169.254            link#5             UCS             2        0     en0
192.168.1          link#5             UCS             6        0     en0
192.168.1.74/32    link#5             UCS             3        0     en0
192.168.1.74       6c:40:8:b0:f5:58   UHLWIi          2        8     lo0
192.168.1.117      70:56:81:f1:22:73  UHLWIi          5     1098     en0    856
192.168.1.122      64:9a:be:8f:65:8a  UHLWIi          2      300     en0    651
192.168.1.212      50:7a:55:9c:52:c6  UHLWIi          2      244     en0    101
192.168.1.254/32   link#5             UCS             3        0     en0
192.168.1.254      5c:dc:96:37:e5:46  UHLWIir         7     1264     en0   1196
192.168.1.255      link#5             UHLWbI          2      280     en0
192.168.192/22     10.200.200.93      UGSc            2        0   utun3
192.168.196/22     10.200.200.93      UGSc            2        0   utun3
224.0.0            link#5             UmCS            3        0     en0
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          2        0     en0
255.255.255.255/32 link#5             UCS             3        0     en0
255.255.255.255    link#5             UHLWbI          2      189     en0
```

**Comment by vieira** [comment] 2016-06-25 00:22
Hi @craigwatson 

`0/1` together with `128.0/1` will route all your traffic through `10.200.200.93`/`utun3` unless there is a more specific route (OpenVPN installs these to effectively set your default route without having to explicitly change/override it). 

For `10.10.216.0/22` it seems to me there isn't, so the traffic is getting routed through the OpenVPN tunnel and the pf rule that would route it to `lo0` does not seem to be executed, although I don't understand why yet.

Can you try to run OpenVPN, then run `route add -host 10.10.216.0/22 -interface lo0` and only after launch sshuttle? In the mean time I will set up OpenVPN on some OSX machine to have a look.

Thanks!

**Comment by craigwatson** [comment] 2016-06-25 10:41
Perfect, running `sudo route add -net 10.10.216.0/22 -interface lo0` (rather than `-host`) works!

Unsure what the next steps are - would it be beyond the scope of sshuttle to add `lo0` routing for the remote subnets on OSX only?

**Comment by vieira** [comment] 2016-06-25 18:46
Good to know. 👍 I installed OpenVPN on OpenBSD and configured all traffic to go through it, then launched sshuttle and it worked without problems, so it is possible that there is some bug or weird behavior in darwin's implementation of pf.

I will test on FreeBSD to check if it behaves the same as OSX.

If I am able to get a better understanding of what is actually going on maybe I can slightly tweak the rules to avoid it. If it turns out that the only way is adding routes (and if we add them we will also have to write code to remove on exit)... I don't know if that's something we should do, we will have to ask @brianmay.

**Comment by vieira** [comment] 2016-06-26 16:50
Working as expected on FreeBSD. This problem seems to be specific do darwin's implementation of pf.

**Comment by craigwatson** [comment] 2016-06-26 17:26
Interesting, thanks for checking this out. Have you been able to reproduce on OSX?

**Comment by vieira** [comment] 2016-06-27 21:32
Hi,

Yes, I was able to reproduce the problem exactly as reported by you on OSX using both Tunnelblick and Viscosity OpenVPN clients. The problem is probably on darwin's implementation of pf.

**Comment by vieira** [comment] 2016-06-28 19:50
So, pf route-to should bypass the routing table and route the packet through the interface specified in the rule. FreeBSD and OpenBSD behave as expected but in OSX the routing table is used and the route-to rule is ignored.

Opened bug 27061884 with Apple.

Can be reproduced without sshuttle or openvpn with:
```
# Add a route for a subnet <A> through some interface (other than lo0)
sudo route add -net <A> -interface en0
# add the following pf rules, where <B> is a subnet in <A>
sudo pfctl -e
sudo pfctl -f /dev/stdin
table <forward_subnets> {<B>,!127.0.0.1/8}
rdr pass on lo0 proto tcp to <forward_subnets> -> 127.0.0.1 port 12300
pass out route-to lo0 inet proto tcp to <forward_subnets> keep state

nc -l 12300
curl -I <B> -vvv
# nothing gets routed to nc
```

**Comment by brianmay** [comment] 2016-08-06 11:17
Looks like this is an OSX issue that has been reported upstream to Apple. Unfortunately, I don't think there is anything more we can do here. Closing.

**Closed by brianmay** 2016-08-06 11:17 UTC
Labels: MacOSX

**Comment by databus23** [comment] 2017-02-10 15:53
@vieira Any response form Apple on the mentioned bug?

**Comment by vieira** [comment] 2017-02-10 15:59
Hello,

They acknlowdged but did not give any indication of whether or when a fix would be released :(

**Comment by jamshid** [comment] 2017-04-29 18:56
Is there any way to link to the Apple issue, would more people complaining help?

Btw I thought I could workaround this by running a `dnsmasq` on my macos that forwards to a `dnsmasq` in the remote network, but I can't seem to set my DNS when vpn'd. Is that the Apple bug, or am I missing something? I'm using Viscosity (OpenVPN).

Everything works, except I can't seem to make macOS Sierra 10.12.4 use my local dnsmasq. 
```
# Start a local DNS server, it forwards to a remote DNS server in the sshuttle network.
# Btw the remote DNS server runs on a weird port (docker), but that seems fine.
$ sudo dnsmasq --cache-size=0 -k -a 127.0.0.1 '--server=172.30.15.3#4253' &
# I can access myremotehost via sshuttle. The name is resolved by remote DNS
$ dig @127.0.0.1 myremotehost
...
;; ANSWER SECTION:
myremotehost.			409	IN	A	172.19.0.25
...
# I can access myremotehost by ip
$ curl -i 172.19.0.25
HTTP/1.1 200 OK
...
# So I assume all I need to do is make my macbook use the local dnsmasq
$ sudo bash -c 'echo nameserver 127.0.0.1 > /etc/resolv.conf'
# Name resolution seems fine
$ dig myremotehost
...
;; ANSWER SECTION:
myremotehost.			409	IN	A	172.19.0.25
...
# Why doesn't curl resolve the same as dig?!
$ curl -i myremotehost
curl: (6) Could not resolve host: myremotehost
```

I verified it's not a DNS caching issue by clearing it:
 `dscacheutil -flushcache; sudo killall -HUP mDNSResponder`

**Comment by majormoses** [comment] 2018-10-02 18:56
I dont think osx honors `/etc/resolv.conf` DNS behavior on macs have always been a moving target with little to no documentation under the hood. Some versions require using `networksetup` command while other versions rely on different commands.

**Comment by databus23** [comment] 2019-09-18 06:37
@vieira I'm still suffering from this. Any updates from Apple on the mentioned bug report?

**Comment by RichardoC** [comment] 2020-07-30 16:57
Given that this is still an issue, can we have sshuttle do "sudo route add -net $subnet -interface lo0" if it detect's it is on macos?
I'm using macos 10.15.6 (Catalina) and sshuttle 0.78.3

**Comment by isshwar** [comment] 2020-08-31 13:34
Hi,

I also face the same issue. Is it like this is an issue with macos and not with sshuttle. If it is with mac, is this still needs to be fixed?

**Comment by irqpoll** [comment] 2021-02-16 10:27
Hello,

What happens is as follows:
When you ssh to the destination host which is "behind" sshuttle, because the default route is via _utun_ interface, the source IP address used for this flow will be the utun IP address.
Initial SYN packets gets redirected to lo0 (pf rules). On lo0 interface packet will look like this:
utun IP -> destination_ssh_server SYN

The SYN-ACK packet (return traffic destined to utun IP) will be routed according to the routing table, in this case it will be routed via utun interface. And here is the problem, the SYN-ACK packet is not consumed by the macos, but instead it is being sent over utun interface. If you listen on the remote side of the tunnel you will get those SYN-ACK packets. Most of the times VPN servers don't forward those packets back, hence macos cannot consume SYN-ACK packets and this is why our 3-way handshake never completes. 

Just as an exercise we can route packets back on the VPN server, but this is very non-optimal.

The question is why MacOS instead of consuming packets originated on localhost and destined to utun IP address, it forwards them over utun interface. The answer is in the routing table. When an utun interface is created a route entry is created for the utun's IP address, but this route instead of pointing to the **lo0** interface, it is pointing to _utun_ interface. This is why our packets localy created and destined to utun's IP address are being forwarded over the tunnel.
As a consequence we can't ping utun's IP address from our terminal.

For each IP address configured on its interfaces we should have a route entry pointing to the lo0, this informs the host to consume packets destined to those IPs. MacOS installs a wrong route in the routing table for utun's IP address. 
I think this should be reported to Apple.

**Comment by craigwatson** [comment] 2021-02-26 20:17
@irqpoll this does (finally!) work around the issue for me, I'm able to programatically get the wifi adapter's IP and prepend  the `-b` flag to the `ssh` command.

**Comment by vgvassilev** [comment] 2021-03-09 14:02
@irqpoll, thanks for the detailed explanation. I think this is what I see on my end as well.

In my setup I route all traffic via a bastion `sshuttle --dns -r bastion 0/0`, then I use GlobalConnect to make a VPN (more details [here](https://github.com/sshuttle/sshuttle/issues/563#issuecomment-793838327)). I cannot seem to make it work by specifying the `ssh -b local_ip` neither with `ssh -b bastion_ip`. Is there another workaround that can help here?

**Comment by irqpoll** [comment] 2021-03-09 16:10
@vgvassilev, just to confirm, you are running:
`ssh -b local_ip remote_ssh_server`

Where _local_ip_ is the IP address on your _enX_ interface, not _utun_ interface.

**Comment by vgvassilev** [comment] 2021-03-10 19:02
@irqpoll, yes that is correct :(
