### ISSUE TITLE
Ubuntu 16.04 Gnome - Shuttle Master UDP issues

### ISSUE THREAD

**Issue by DiagonalArg** [sshuttle/sshuttle#106] opened 2016-07-10 07:17 UTC
sshuttle-master is running fine for TCP.  Output appears to indicate that with --method=tproxy it is accepting/sending UDP, but that doesn't seem to be the case.  I find I am unable to ping anything and already open connections are shut down.

```
sudo SSH_AUTH_SOCK="$SSH_AUTH_SOCK" su                                                                                                                   
ip route add local default dev lo table 100
ip rule add fwmark 1 lookup 100
./run --method=tproxy --disable-ipv6 -vvv --pidfile=/tmp/sshuttle.pid -r user@server.com 0/0 -x <server.ip>
```

[Output](https://github.com/sshuttle/sshuttle/files/355882/sshuttleout.git.txt).  

I notice this line in the output: `/proc/net/route: No such file or directory`.  It's odd because that file does exist.

192.168.10.1 is the router, and 192.168.10.10 is my machine.

**Comment by vieira** [comment] 2016-07-10 09:00
Hello @DiagonalArg,

ping is ICMP so it is not a good test for the problem you are reporting (UDP issues). I see you are sending all you traffic through `<server>` so any UDP traffic to the Internet should go through, can you test something like ``dig github.com @8.8.8.8`` or ``sudo ntpdate-debian``.

**Comment by DiagonalArg** [comment] 2016-07-10 18:45
Well, the problem I'm reporting is that I don't appear to be able to do *anything* on the net; but here is the [output](https://github.com/sshuttle/sshuttle/files/356142/sshuttleout.git.txt) when running:

```
me@machine:~$ dig github.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> github.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I get the following result regardless of whether I use sshuttle or not, because when I'm not using sshuttle, this network forces me to use their DNS and otherwise closes UDP:

```
me@machine:~$ dig github.com @8.8.8.8

; <<>> DiG 9.10.3-P4-Ubuntu <<>> github.com @8.8.8.8
;; global options: +cmd
;; connection timed out; no servers could be reached
```

`ntpdate` is not installed here.  Let me know if you want me to install it or run something else.

**Comment by vieira** [comment] 2016-07-11 00:57
Hello,

So if I understand correctly, on the machine running sshuttle the connection times out while running dig github.com @8.8.8.8. On the remote end (server) you ran the same dig github.com @8.8.8.8 and it worked. Is that right? Can you try running sshuttle with 8.8.0.0/16 instead of 0/0 -x \<server.ip\> and trying dig github.com @8.8.8.8 again from the machine running sshuttle? Please use -vvv and paste the output.

Many thanks!

**Comment by DiagonalArg** [comment] 2016-07-11 06:13
> So if I understand correctly, on the machine running sshuttle the connection times out while running dig github.com @8.8.8.8. On the remote end (server) you ran the same dig github.com @8.8.8.8 and it worked. Is that right?

Yes, on the machine running sshuttle it times out, but on the server, I get this:

```
me@server.com>  dig github.com @8.8.8.8

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.47.rc1.el6 <<>> github.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59306
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;github.com.			IN	A

;; ANSWER SECTION:
github.com.		205	IN	A	192.30.253.112

;; Query time: 4 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Jul 11 05:55:13 2016
;; MSG SIZE  rcvd: 44
```

I also experimented running a command line torrenting program using UDP on the server, and it worked.  So the server is definitely good with UDP.

> Can you try running sshuttle with 8.8.0.0/16 instead of 0/0 -x <server.ip> and trying dig github.com @8.8.8.8 again from the machine running sshuttle? Please use -vvv and paste the output.

That works.  The output of `dig` is below, and [this is sshuttle's output](https://github.com/sshuttle/sshuttle/files/356508/sshuttleout.git.txt).  The sshuttle command I used is:

`./run --method=tproxy --disable-ipv6 -vvv --pidfile=/tmp/sshuttle.pid -r me@server.com 8.8.0.0/16`

```
machine running sshuttle> dig github.com @8.8.8.8 

; <<>> DiG 9.10.3-P4-Ubuntu <<>> github.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9608
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             174     IN      A       192.30.253.113

;; Query time: 172 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Jul 10 22:59:47 PDT 2016
;; MSG SIZE  rcvd: 55

```

**Comment by vieira** [comment] 2016-07-12 16:32
@DiagonalArg I also noticed some problems when using 0/0. I might take a look but I am not familiar with tproxy. Maybe @brianmay knows what might be wrong.

**Comment by brianmay** [comment] 2016-07-13 08:20
tproxy can be somewhat difficult to understand and debug when it isn't working.

I have found that some kernels seem to have broken TPROXY support. No idea if the Kernel that comes with Ubuntu 16.04  is good or not, sorry.

Eventually I will have to upgrade my two Ubuntu 14.04 systems to 16.04, when I do that I should be able to test this myself.

**Comment by DiagonalArg** [comment] 2016-07-21 20:28
@brianmay - what systems do work?  Ubuntu 14.04, yes?  Others?

(Travelling, so will be slow on the response, but still *very* interested.)

**Comment by brianmay** [comment] 2016-07-23 10:43
Unfortunately I have a back log of things to do right now. However yes, will be interesting to do tests. I would assume that all recent kernels, including 16.04 should be fine, but cannot actually guarantee it.

**Comment by DiagonalArg** [comment] 2016-07-23 19:00
@brianmay - Well, if you have a debug version of this, I can install & run.

Is that a pure vanilla Ubuntu 14.04 that you're using sshuttle/tproxy with?

**Comment by brianmay** [comment] 2016-07-24 06:49
I generally use Debian more often then Ubuntu at the moment.

**Comment by DiagonalArg** [comment] 2016-07-24 15:16
Ok, perhaps *I'll* install debian in a VM.

But, *does* sshuttle/tproxy work in 14.04??

**Comment by vieira** [comment] 2016-07-24 15:33
@DiagonalArg the problem you are having only happens when you have 0/0 in the subnets, right?

**Comment by DiagonalArg** [comment] 2016-07-26 20:03
@vieira - Well, all I've tried is `0/0 -x <server>` and `8.8.0.0/16`; but yes, that appears to be the problem.

**Comment by vieira** [comment] 2016-07-30 19:54
@DiagonalArg Not being an expert in tproxy I have tried a few things today and managed to get it working with 0/0 as long as I use the right combination of excludes `-x <server_ip> -x <client_ip>` where `<client_ip>` is the IP of the client connecting via ssh to the server.

In my tests I was connecting over the internet so I set it to the client public IP. If your server is in the same network you should probably use the IP of the client in that same network.

If you don't have physical access to the client and are connecting to it via, e.g., ssh, to start sshuttle you also have to exclude the IP of the machine you are connecting from, in my case, the public IP of my laptop, otherwise the ssh connection will be closed as soon as the firewall rules are set (I end up with `-x <server_ip> -x <client_ip> -x <laptop_ip>`).

Let me know if this also works for you. Tested on Ubuntu 16.04.1.

**Comment by vieira** [comment] 2016-08-03 01:40
Do you have any other iptables rules on the client or server? Can you share `iptables-save`?

**Comment by DiagonalArg** [comment] 2016-08-11 17:35
@vieira - nothing special.  I've [attached it here](https://github.com/sshuttle/sshuttle/files/413823/iptables.txt).  This is with sshuttle off.

**Comment by DiagonalArg** [comment] 2016-08-20 15:41
@vieira - Ok, I got `dig github.com @8.8.8.8` to work by excluding all *local* IP's, along with the my public IP and the server's public IP.  Unfortunately, when I try to start Transmission, sshuttle then crashes.  Here's [the output](https://github.com/sshuttle/sshuttle/files/428390/sshuttle.out.txt).

(Again, apologies for slowness, but I'm travelling.)

**Comment by vieira** [comment] 2016-08-20 22:11
Hi @DiagonalArg

Sorry for the delay. I will take a look, this seems like something we should fix. You are running from HEAD right?

Thanks!

**Comment by vieira** [comment] 2016-08-21 00:17
I was having the same problem but I was some commits backs on my test machine, after a ``git pull`` it no longer happened. What is stranger to me is that I had to put --ns-hosts 8.8.8.8 to get that line of code to even execute (and even then it did without throwing the error). Could you please make sure that you are on the latest commit of master?

However I still got problems running transmission over sshuttle:
```
(...)
 s: UDP response: 20 bytes
 s:  > channel=4 cmd=UDP_DATA len=41 (fullness=27460)
 s: Waiting: 5 r=[4, 6, 8, 9] w=[5] x=[] (fullness=27501/0)
 s:   Ready: 5 r=[] w=[5] x=[]
 s: mux wrote: 49/49
 s: Waiting: 5 r=[4, 6, 8, 9] w=[] x=[] (fullness=27501/0)
c :   Ready: 4 r=[9] w=[] x=[]
c : <  channel=4 cmd=UDP_DATA len=41
c : doing send from (b'93.230.168.217', 17676) to ('51.254.204.93', 51413)
 s:   Ready: 5 r=[9] w=[] x=[]
 s: UDP response: 30 bytes
 s:  > channel=4 cmd=UDP_DATA len=50 (fullness=27501)
 s: Waiting: 5 r=[4, 6, 8, 9] w=[5] x=[] (fullness=27551/0)
 s:   Ready: 5 r=[] w=[5] x=[]
 s: mux wrote: 58/58
 s: Waiting: 5 r=[4, 6, 8, 9] w=[] x=[] (fullness=27551/0)
c : <  channel=4 cmd=UDP_DATA len=50
c : doing send from (b'80.237.22.203', 51413) to ('51.254.204.93', 51413)
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> iptables -t mangle -D OUTPUT -j sshuttle-m-12300
>> iptables -t mangle -F sshuttle-m-12300
>> iptables -t mangle -X sshuttle-m-12300
>> iptables -t mangle -D PREROUTING -j sshuttle-t-12300
>> iptables -t mangle -F sshuttle-t-12300
>> iptables -t mangle -X sshuttle-t-12300
>> iptables -t mangle -F sshuttle-d-12300
>> iptables -t mangle -X sshuttle-d-12300
firewall manager: undoing /etc/hosts changes.
 s:   Ready: 5 r=[9] w=[] x=[]
 s: UDP response: 30 bytes
 s:  > channel=4 cmd=UDP_DATA len=49 (fullness=27551)
 s: Waiting: 5 r=[4, 6, 8, 9] w=[5] x=[] (fullness=27600/0)
 s:   Ready: 5 r=[] w=[5] x=[]
 s: mux wrote: 57/57
 s: Waiting: 5 r=[4, 6, 8, 9] w=[] x=[] (fullness=27600/0)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/sshuttle/sshuttle/__main__.py", line 4, in <module>
    sys.exit(main())
  File "/root/sshuttle/sshuttle/cmdline.py", line 74, in main
    opt.daemon, opt.pidfile)
  File "/root/sshuttle/sshuttle/client.py", line 726, in main
    seed_hosts, auto_hosts, auto_nets, daemon)
  File "/root/sshuttle/sshuttle/client.py", line 511, in _main
    ssnet.runonce(handlers, mux)
  File "/root/sshuttle/sshuttle/ssnet.py", line 585, in runonce
    h.callback(s)
  File "/root/sshuttle/sshuttle/ssnet.py", line 483, in callback
    self.handle()
  File "/root/sshuttle/sshuttle/ssnet.py", line 471, in handle
    self.got_packet(channel, cmd, data)
  File "/root/sshuttle/sshuttle/ssnet.py", line 431, in got_packet
    callback(cmd, data)
  File "/root/sshuttle/sshuttle/client.py", line 369, in <lambda>
    chan, data, method, listener, dstip=srcip)
  File "/root/sshuttle/sshuttle/client.py", line 354, in udp_done
    method.send_udp(sock, srcip, dstip, data)
  File "/root/sshuttle/sshuttle/methods/tproxy.py", line 137, in send_udp
    sender.bind(srcip)
OSError: [Errno 98] Address already in use
```

**Comment by brianmay** [comment] 2016-08-21 04:01
Any ideas why it is returning "Address already in use"? Suspect the proposed patch is a work around, it isn't going to solve the root cause.

Normally this error would mean "we cannot bind to this port because it is already in use." 

I am wondering if it is due to a previous binding on (b'80.237.22.203', 51413) and the operating system still considers it in use, even after we call the socket.close() method. I could understand this with TCP, seems surprising for UDP however.

Alternatively, maybe something is binding to this port without SO_REUSEADDR???

**Comment by DiagonalArg** [comment] 2016-08-24 14:53
@vieira 

> You are running from HEAD right?

Not sure of the vernacular, but 4 days ago I used the "download zip" link under "clone or download" on the code page.  That link is:  https://github.com/sshuttle/sshuttle/archive/master.zip

**Comment by DiagonalArg** [comment] 2016-08-24 15:53
@vieira 

> I was having the same problem but I was some commits back on my test machine, after a git pull it no longer happened. What is stranger to me is that I had to put --ns-hosts 8.8.8.8 to get that line of code to even execute (and even then it did without throwing the error). Could you please make sure that you are on the latest commit of master?

I've just re-downloaded and find the same problem.  Crash on `dig`.  Here is the [ouput](https://github.com/sshuttle/sshuttle/files/435101/sshuttle.out.txt).

**Comment by DiagonalArg** [comment] 2016-08-24 16:12
@vieira 

I tried the [patch you offered](https://github.com/vieira/sshuttle/commit/864e95b633faf571e9bdf0b40f0a834541d568a7#diff-ac0b595db2a1f11bb5eae88c749b89bb), but the results are unchanged, viz a crash on dig.  [Output](https://github.com/sshuttle/sshuttle/files/435140/sshuttle.out.txt).

**Comment by vieira** [comment] 2016-08-24 17:29
@DiagonalArg the patch is for another problem, one that I experienced after I stopped having the problem you reported. I will try once more to reproduce that problem, since it seems it is still happening to you on HEAD, right?

**Comment by DiagonalArg** [comment] 2016-08-25 20:07
@vieira - to repeat, assuming "HEAD" is what I get at this link: https://github.com/sshuttle/sshuttle/archive/master.zip

then, yes, the problem is continuing as of yesterday.  If you want me to test something else, let me know!

**Comment by vieira** [comment] 2016-08-26 21:46
@DiagonalArg I just downloaded from that link and tried ``dig github.com @8.8.4.4`` and some variations: other domains, with `8.8.8.8`, etc. No problems.

Ran both the following commands:

```
./run -r root@server --method=tproxy --disable-ipv6 -vvv 0/0 -x server -x client -x my_laptop --ns-hosts 8.8.8.8
```

and

```
./run -r root@server --method=tproxy --disable-ipv6 -vvv 0/0 -x server -x client -x my_laptop
```

Client is running Python 3.5 and:
```
lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

server is running Python 3.4.3 and
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

Now I might be wrong but looking at your logs I don't think you are running the version of sshuttle you think you are running. Your traceback is

```
(...)
 s: <  channel=7 cmd=UDP_DATA len=50
 s: Incoming UDP request channel=7, cmd=16909
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 37, in <module>
  File "sshuttle.server", line 334, in main
  File "sshuttle.ssnet", line 583, in runonce
  File "sshuttle.ssnet", line 481, in callback
  File "sshuttle.ssnet", line 469, in handle
  File "sshuttle.ssnet", line 429, in got_packet
  File "sshuttle.server", line 317, in <lambda>
  File "sshuttle.server", line 303, in udp_req
TypeError: a bytes-like object is required, not 'str'
```

Line 303, in udp_req... but if you look into the current HEAD, [server.py#l303](https://github.com/sshuttle/sshuttle/blob/1ffc3f52a112a7f1952d29b414155852ef10a29e/sshuttle/server.py#303) is in dns_req... There is no lambda in line 317 either.

So please make sure you don't have some older version installed that is getting executed when you think you are running the latest version.

**Comment by vieira** [comment] 2016-08-26 21:54
@brianmay It is a workaround as I don't really know what the root cause is yet. This is unrelated but I also get some `read: err was: [Errno 11] Resource temporarily unavailable` with some frequency but without any other consequences. Not sure about what those are either. Do you know?

I will have another look at the bind error, taking your suggestions into consideration. Thanks!

**Comment by DiagonalArg** [comment] 2016-08-27 15:54
@vieira - well, I do have sshuttle 0.78.0 installed, but I don't think that's an issue.  The command I am running is:

```
ip route add local default dev lo table 100; ip rule add fwmark 1 lookup 100
/home/user/Downloads/sshuttle_0.78.1_git/run --python=/home/<user>/.linuxbrew/bin/python3 --method=tproxy --disable-ipv6 -vvv --pidfile=/tmp/sshuttle.pid -r user@server.com 0/0 -x 192.168.0.0/16 -x 10.0.0.0/8 -x 172.16.0.0/12 -x <my.public.ip> -x <server.public.ip>
```

Where that directory `~/Downloads/sshuttle_0.78.1_git` is the location of the downloaded master.

Note that I *just* added the `--python=` switch for fear that sshuttle might have some trouble with my PATH, which has been set on the remote machine to:

`/home/<user>/.linuxbrew/bin:/home/<user>/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin`

It is still making no difference.  I am crashing on dig (output, below).

My local machine is:

```
lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

Python versions available locally:

```
/usr/bin/python               <-- that is version 2.7.12
/usr/bin/python2.7          <-- that is version 2.7.12
/usr/bin/python2-config      
/usr/bin/python2-pbr  
/usr/bin/python3.5          <-- version 3.5.2
/usr/bin/python3m
/usr/bin/python2  
/usr/bin/python2.7-config  
/usr/bin/python2-jsonschema  
/usr/bin/python3      
/usr/bin/python3.5m  
/usr/bin/python-config
```

My remote machine is CentOS.  This is all I can find for the version:

`CloudLinux Server release 6.8 (Oleg Makarov)`

Python versions available on the server:

```
/usr/bin/python  
/usr/bin/python2  <-- that's version 2.6.6
/usr/bin/python2.6  
/usr/bin/python2.6-config  
/usr/bin/python-config

```

Also available on server, via linuxbrew:

```
~/.linuxbrew/bin/python3  <-- that's version 3.5.2
~/.linuxbrew/bin/python3.5
```

Here then is my [output](https://github.com/sshuttle/sshuttle/files/440731/sshuttle.out.txt), which was a crash on `dig github.com @8.8.8.8`

**Comment by vieira** [comment] 2016-08-27 18:14
Oh that is an issue. Run just executes the module `sshuttle` from your Python path. The old version of sshuttle that is installed is installed to your python path, the version you just downloaded is not. So even though you are running the run script of HEAD, the module that is getting executed is the old one. I am afk right now but you can try `export PYTHONPATH=/where/you/downloaded/sshuttle/head` and only then executing the run command. Prefixing the run with PYTHONPATH=... might be enough but I can't test right now.

**Comment by DiagonalArg** [comment] 2016-08-27 19:49
@vieira - OMG.

Having trouble knowing how to check if it's working.  First of all, do I want: `PYTHONPATH=/home/user/Downloads/sshuttle_0.78.1_git`

or:

`PYTHONPATH=/home/user/Downloads/sshuttle_0.78.1_git/sshuttle`

I tried both, then I tried:  `python3.5 -m "sshuttle" --version`, since my installed version is 0.78.0, while the master is 0.78.1, but it keeps failing:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dev/Downloads/sshuttle_0.78.1_git/sshuttle/__main__.py", line 3, in <module>
    from sshuttle.cmdline import main
  File "/home/dev/Downloads/sshuttle_0.78.1_git/sshuttle/cmdline.py", line 3, in <module>
    import sshuttle.client as client
  File "/home/dev/Downloads/sshuttle_0.78.1_git/sshuttle/client.py", line 355, in <module>
    method.send_udp(sock, srcip, dstip, data)
NameError: name 'method' is not defined
```

I'm sorry.  Is there a better way to do this?  I do need to have a installed version for my scripts that use it.

**Comment by vieira** [comment] 2016-08-27 23:00
So this is what I did:
```
wget https://github.com/sshuttle/sshuttle/archive/master.zip
unzip master.zip
cd sshuttle-master
export PYTHONPATH="."
./run --version
# Python 3.5.1+
# unknown
./run -r root@<server> --method=tproxy --disable-ipv6 -vvv 0/0 -x <server_ip> -x <client_ip> -x <laptop_ip>
```

**Comment by DiagonalArg** [comment] 2016-08-28 15:42
Ok!  `dig` now works!!  Like you, it still crashes on Transmission.

I must say this is very interesting, though.  From `/root`:

```
$ /home/user/Downloads/sshuttle_0.78.1_git/run --version                     │
Python 3.5.2                                                                                    │
0.78.0
```

From the location of sshuttle.master:

```
$ ./run --version
Python 3.5.2
unknown
```

One other thing did clear up.  That error two posts back (and below), is due to your patch.  Without the patch it doesn't appear.

```
./run --version
Python 3.5.2
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dev/Downloads/sshuttle_0.78.1_git/sshuttle/__main__.py", line 3, in <module>
    from sshuttle.cmdline import main
  File "/home/dev/Downloads/sshuttle_0.78.1_git/sshuttle/cmdline.py", line 3, in <module>
    import sshuttle.client as client
  File "/home/dev/Downloads/sshuttle_0.78.1_git/sshuttle/client.py", line 355, in <module>
    method.send_udp(sock, srcip, dstip, data)
```

I will try Transmission with your patch, though.  I'll let you know what happens.

**Comment by brianmay** [comment] 2016-08-30 08:55
I just pushed a series of changes to (hopefully) fix some of the reported problems with the run command. Except just realised that the change to PYTHONPATH assumes you are running from the same directory. Will fix that.

**Comment by brianmay** [comment] 2016-08-30 09:04
Ok, now fixed run so it should be able to identify the correct directory, even when run from another directory.

**Comment by DiagonalArg** [comment] 2016-08-31 17:31
@brianmay - Brian, is this expected?

```
/home/user/Downloads/sshuttle-master# ./run --version
Traceback (most recent call last):
  File "./setup.py", line 65, in <module>
    keywords="ssh vpn",
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "build/bdist.linux-x86_64/egg/setuptools_scm/integration.py", line 19, in version_keyword
  File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 104, in get_version
  File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 82, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/home/dev/Downloads/sshuttle-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
unknown
```

**Comment by brianmay** [comment] 2016-09-01 08:57
Yes, I forgot about this when making the previous change. If you download using the zip file it can't tell what version it is. So maybe we should fallback to "unknown" or something in this case.

First a question: Why do you prefer downloading the zip file? Wouldn't it be more convenient to clone the git repository?

**Comment by brianmay** [comment] 2017-11-07 22:38
I am losing track of this bug report, so many unrelated issues that have been fixed. If the original problem has not been fixed in git master, can you please open a new bug report? Thanks.

**Closed by brianmay** 2017-11-07 22:38 UTC
Labels: help wanted

**Comment by DiagonalArg** [comment] 2017-11-20 07:10
@brianmay - you, I and @vieira worked on this diligently, and after some side issues were brought into the mix, we found that we could get `dig` to work, but Transmission did not (either for I or @vieira).  While I very much want a UDP solution for Transmission and VoIP, I dropped it because neither were working.  Perhaps I should try again?

**Comment by vieira** [comment] 2017-11-20 09:24
Hello @DiagonalArg,

There is also some discussion in #112, for more context.
