### ISSUE TITLE
python 3.10 importlib.metadata.PackageNotFoundError

### ISSUE THREAD

**Issue by rderooy** [sshuttle/sshuttle#744] opened 2022-03-09 14:13 UTC
I have the repo cloned locally and when I build it, and then try to run sshuttle it fails with importlib.metadata.PackageNotFoundError.

I have ``export PYTHONPATH=$HOME/lib/python/`` defined in my ``.bashrc``.

Running sshuttle fails with:

```
# sshuttle
Traceback (most recent call last):
  File "/home/rderooy/bin/sshuttle", line 33, in <module>
    sys.exit(load_entry_point('sshuttle==1.1.1.dev28+g9431bb7', 'console_scripts', 'sshuttle')())
  File "/home/rderooy/bin/sshuttle", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 928, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for sshuttle
```

Building log
```bash
# ./setup.py build
/usr/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running build
running build_py
copying sshuttle/version.py -> build/lib/sshuttle
running build_scripts
```
Install log
```bash
# ./setup.py install --home ~
/usr/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing sshuttle.egg-info/PKG-INFO
writing dependency_links to sshuttle.egg-info/dependency_links.txt
writing entry points to sshuttle.egg-info/entry_points.txt
writing top-level names to sshuttle.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'docs/_build'
adding license file 'LICENSE'
writing manifest file 'sshuttle.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying sshuttle/version.py -> build/lib/sshuttle
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/__init__.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/__main__.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/sdnotify.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/ssyslog.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/stresstest.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/sudoers.py -> build/bdist.linux-x86_64/egg/sshuttle
creating build/bdist.linux-x86_64/egg/sshuttle/methods
copying build/lib/sshuttle/methods/__init__.py -> build/bdist.linux-x86_64/egg/sshuttle/methods
copying build/lib/sshuttle/methods/nat.py -> build/bdist.linux-x86_64/egg/sshuttle/methods
copying build/lib/sshuttle/methods/nft.py -> build/bdist.linux-x86_64/egg/sshuttle/methods
copying build/lib/sshuttle/methods/pf.py -> build/bdist.linux-x86_64/egg/sshuttle/methods
copying build/lib/sshuttle/methods/ipfw.py -> build/bdist.linux-x86_64/egg/sshuttle/methods
copying build/lib/sshuttle/methods/tproxy.py -> build/bdist.linux-x86_64/egg/sshuttle/methods
copying build/lib/sshuttle/hostwatch.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/cmdline.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/linux.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/ssnet.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/server.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/ssh.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/assembler.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/firewall.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/helpers.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/client.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/options.py -> build/bdist.linux-x86_64/egg/sshuttle
copying build/lib/sshuttle/version.py -> build/bdist.linux-x86_64/egg/sshuttle
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/__main__.py to __main__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/sdnotify.py to sdnotify.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/ssyslog.py to ssyslog.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/stresstest.py to stresstest.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/sudoers.py to sudoers.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/methods/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/methods/nat.py to nat.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/methods/nft.py to nft.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/methods/pf.py to pf.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/methods/ipfw.py to ipfw.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/methods/tproxy.py to tproxy.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/hostwatch.py to hostwatch.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/cmdline.py to cmdline.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/linux.py to linux.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/ssnet.py to ssnet.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/server.py to server.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/ssh.py to ssh.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/assembler.py to assembler.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/firewall.py to firewall.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/helpers.py to helpers.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/client.py to client.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/options.py to options.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/sshuttle/version.py to version.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/sudoers-add -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sudoers-add to 775
copying sshuttle.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sshuttle.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sshuttle.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sshuttle.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sshuttle.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
sshuttle.__pycache__.client.cpython-310: module references __file__
sshuttle.__pycache__.sudoers.cpython-310: module references __file__
creating 'dist/sshuttle-1.1.1.dev28+g9431bb7-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sshuttle-1.1.1.dev28+g9431bb7-py3.10.egg
removing '/home/rderooy/lib/python/sshuttle-1.1.1.dev28+g9431bb7-py3.10.egg' (and everything under it)
creating /home/rderooy/lib/python/sshuttle-1.1.1.dev28+g9431bb7-py3.10.egg
Extracting sshuttle-1.1.1.dev28+g9431bb7-py3.10.egg to /home/rderooy/lib/python
sshuttle 1.1.1.dev28+g9431bb7 is already the active version in easy-install.pth
Installing sudoers-add script to /home/rderooy/bin
Installing sshuttle script to /home/rderooy/bin

Installed /home/rderooy/lib/python/sshuttle-1.1.1.dev28+g9431bb7-py3.10.egg
Processing dependencies for sshuttle==1.1.1.dev28+g9431bb7
Finished processing dependencies for sshuttle==1.1.1.dev28+g9431bb7
```

**Comment by yjftsjthsd-g** [comment] 2022-03-21 03:55
Okay, so I can reproduce with this Dockerfile:
```
FROM python:3.10-slim
RUN apt-get update && apt-get install -qy --no-install-recommends git
RUN useradd -m user
USER user
RUN git clone --depth 1 https://github.com/sshuttle/sshuttle.git /home/user/sshuttle
RUN mkdir -p /home/user/lib/python/
ENV PYTHONPATH=/home/user/lib/python/
WORKDIR /home/user/sshuttle
RUN ./setup.py build
RUN ./setup.py install --home ~
CMD /home/user/bin/sshuttle
```

But it seems to work if I set `PYTHONPATH=/home/user/lib/python/sshuttle-0.1.dev1+g5719d42-py3.10.egg/` instead.

More generally, I would suggest that you might consider using a virtualenv for this.

**Comment by yjftsjthsd-g** [comment] 2022-03-22 22:27
It works fine with 3.10 in a virtualenv for me? Again in the form of a Dockerfile to make everything explicit - this works:
```
FROM python:3.10-slim
RUN apt-get update && apt-get install -qy --no-install-recommends git
RUN useradd -m user
USER user
RUN git clone --depth 1 https://github.com/sshuttle/sshuttle.git /home/user/sshuttle
RUN pip install virtualenv
RUN python -m virtualenv ~/venv
RUN /home/user/venv/bin/pip install /home/user/sshuttle
CMD /home/user/venv/bin/sshuttle --version
```

> In any case, there is clearly a problem with sshuttle and python 3.10 where for some reason it cannot find its files.

I don't think so? I can reproduce the failure with 3.9 (and the fix seems to be the same).

**Comment by brianmay** [comment] 2022-03-23 01:39
This also works for me:

```
FROM python:3.10-slim
RUN apt-get update && apt-get install -qy --no-install-recommends git
RUN useradd -m user
USER user
RUN git clone --depth 1 https://github.com/sshuttle/sshuttle.git /home/user/sshuttle
RUN mkdir -p /home/user/lib/python/
ENV PYTHONPATH=/home/user/lib/python/
WORKDIR /home/user/sshuttle
RUN ./setup.py build
RUN pip install .
CMD /home/user/.local/bin/sshuttle
```

Note in this case, the location of the binary has changed.

In general, I believe "pip install" is preferred over "setup.py install", See https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install

**Comment by brianmay** [comment] 2022-04-26 23:41
I think this is a quirk of Python, not a bug in sshuttle, closing.

**Closed by brianmay** 2022-04-26 23:41 UTC
