### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by ishmael1851** [sshuttle/sshuttle#400] opened 2020-03-11 08:33 UTC
I tried running this on Mac using the latest clone of sshuttle.

```
TERMUX_USER="u0_a305"
TERMUX_IP="192.168.43.94"
TERMUX_PORT="8022"
sshuttle -r $TERMUX_USER@$TERMUX_IP:$TERMUX_PORT 0.0.0.0/0 -l 0.0.0.0:0
```
But I got this error

> Environment:
>   USER=u0_a305
>   LOGNAME=u0_a305
>   HOME=/data/data/com.termux/files/home
>   PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
>   SHELL=/data/data/com.termux/files/usr/bin/login
>   ANDROID_DATA=/data
>   ANDROID_ROOT=/system
>   ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
>   ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
>   BOOTCLASSPATH=/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastl
>   EXTERNAL_STORAGE=/sdcard
>   LANG=en_US.UTF-8
>   PREFIX=/data/data/com.termux/files/usr
>   TMPDIR=/data/data/com.termux/files/usr/tmp
>   SSH_CLIENT=192.168.43.37 50007 8022
>   SSH_CONNECTION=192.168.43.37 50007 192.168.43.94 8022
> assembler.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> client: Connected.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "assembler.py", line 40, in <module>
>   File "sshuttle.server", line 297, in main
>   File "/data/data/com.termux/files/usr/lib/python3.8/socket.py", line 544, in fromfd
>     return socket(family, type, proto, nfd)
>   File "/data/data/com.termux/files/usr/lib/python3.8/socket.py", line 231, in __init__
>     _socket.socket.__init__(self, family, type, proto, fileno)
> OSError: [Errno 88] Socket operation on non-socket
> client: fatal: server died with error code 1

The host reports

```
$ sshd -dD
debug1: sshd version OpenSSH_8.2, OpenSSL 1.1.1d  10 Sep 2019
debug1: private host key #0: ssh-rsa SHA256:F8/zXjd/KPuSL7vH+gQbX2nrlN1q/2U0nESv21qcLfA
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:Rm0dYNscHgizvVNBjbcxRWjNFxOxWt1/eeYUpsIzphE
debug1: private host key #2: ssh-ed25519 SHA256:hRrrmhQ3KZLQmkNxDS5UTJWdKx9qNb+1j/qewdGZXyE
debug1: rexec_argv[0]='/data/data/com.termux/files/usr/bin/sshd'
debug1: rexec_argv[1]='-dD'
debug1: Bind to port 8022 on ::.
Server listening on :: port 8022.
debug1: Bind to port 8022 on 0.0.0.0.
Server listening on 0.0.0.0 port 8022.
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: sshd version OpenSSH_8.2, OpenSSL 1.1.1d  10 Sep 2019
debug1: private host key #0: ssh-rsa SHA256:F8/zXjd/KPuSL7vH+gQbX2nrlN1q/2U0nESv21qcLfA
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:Rm0dYNscHgizvVNBjbcxRWjNFxOxWt1/eeYUpsIzphE
debug1: private host key #2: ssh-ed25519 SHA256:hRrrmhQ3KZLQmkNxDS5UTJWdKx9qNb+1j/qewdGZXyE
debug1: inetd sockets after dupping: 3, 3
Connection from 192.168.43.37 port 50198 on 192.168.43.94 port 8022
debug1: Local version string SSH-2.0-OpenSSH_8.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9
debug1: match: OpenSSH_7.9 pat OpenSSH* compat 0x04000000
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_INIT
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: Sending SSH2_MSG_EXT_INFO
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: KEX done
debug1: userauth-request for user u0_a305 service ssh-connection method none
debug1: attempt 0 failures 0
Failed none for u0_a305 from 192.168.43.37 port 50198 ssh2
debug1: userauth-request for user u0_a305 service ssh-connection method publickey
debug1: attempt 1 failures 0
debug1: userauth_pubkey: test pkalg rsa-sha2-512 pkblob RSA SHA256:P9nfVZFzzCmS1fFHKlaliOZad55lnMBSCbZ9PW0BoBI
debug1: temporarily_use_uid: 10305/10305 (e=10305/10305)
debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys
debug1: fd 4 clearing O_NONBLOCK
debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:1: matching key found: RSA SHA256:P9nfVZFzzCmS1fFHKlaliOZad55lnMBSCbZ9PW0BoBI
debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key RSA SHA256:P9nfVZFzzCmS1fFHKlaliOZad55lnMBSCbZ9PW0BoBI found at /data/data/com.termux/files/home/.ssh/authorized_keys:1
debug1: restore_uid: (unprivileged)
Postponed publickey for u0_a305 from 192.168.43.37 port 50198 ssh2
debug1: userauth-request for user u0_a305 service ssh-connection method publickey                                     debug1: attempt 2 failures 0
debug1: temporarily_use_uid: 10305/10305 (e=10305/10305)   debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys                                  debug1: fd 4 clearing O_NONBLOCK
debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:1: matching key found: RSA SHA256:P9nfVZFzzCmS1fFHKlaliOZad55lnMBSCbZ9PW0BoBI                                      debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key RSA SHA256:P9nfVZFzzCmS1fFHKlaliOZad55lnMBSCbZ9PW0BoBI found at /data/data/com.termux/files/home/.ssh/authorized_keys:1                                             debug1: restore_uid: (unprivileged)
debug1: auth_activate_options: setting new authentication options
Accepted publickey for u0_a305 from 192.168.43.37 port 50198 ssh2: RSA SHA256:P9nfVZFzzCmS1fFHKlaliOZad55lnMBSCbZ9PW0BoBI                                                        debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding                              debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch                               debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0                             debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
debug1: server_input_channel_req: channel 0 request env reply 0
debug1: session_by_channel: session 0 channel 0            debug1: session_input_channel_req: session 0 req env
debug1: server_input_channel_req: channel 0 request env reply 0                                                       debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req env
debug1: server_input_channel_req: channel 0 request env reply 0
debug1: session_by_channel: session 0 channel 0            debug1: session_input_channel_req: session 0 req env
debug1: server_input_channel_req: channel 0 request exec reply 1
debug1: session_by_channel: session 0 channel 0            debug1: session_input_channel_req: session 0 req exec
Starting session: command for u0_a305 from 192.168.43.37 port 50198 id 0
debug1: Received SIGCHLD.                                  debug1: session_by_pid: pid 23153
debug1: session_exit_message: session 0 channel 0 pid 23153
debug1: session_exit_message: release channel 0
Received disconnect from 192.168.43.37 port 50198:11: disconnected by user
Disconnected from user u0_a305 192.168.43.37 port 50198
debug1: do_cleanup
```

**Comment by brianmay** [comment] 2020-03-11 09:17
I think this is a duplicate of #381. Closing.

**Closed by brianmay** 2020-03-11 09:17 UTC
